language: python
python:
    - "3.9"
# command to install dependencies
install:
    - pip install -r requirements.txt
services:
    - postgresql
# command to run tests
before_script:
    - psql -c "CREATE USER testing WITH PASSWORD '1234';" -U postgres
    - psql -c "CREATE DATABASE flask;" -U postgres
script:
    - set FLASK_APP=run.py
    - flask db upgrade
    - pytest
